[config]

[tasks.serve]
env_files = [".env.local"]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "--help" }
command = "trunk"
args = ["serve"]

[tasks.build]
env_files = [".env"]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "--help" }
command = "trunk"
# toolchain = "stable"
args = ["build"]
